# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FinalAssignment' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'Alamofire'
  pod 'SQLite.swift', '~> 0.12.0'
  pod 'FMDB'
  # Pods for FinalAssignment
  
end
